"""One-line HTML tear sheet — the quantstats-style shareable report.

    from portlab.report import tear_sheet
    tear_sheet(returns, benchmark, output="my_portfolio.html")

Produces a single self-contained HTML file with headline stats, the full
metrics table, interactive charts, and the worst-drawdowns table. Works
headless; open the file in any browser or share it directly.
"""

from __future__ import annotations

import pandas as pd

from .config import DEFAULT_RF, TRADING_DAYS
from . import metrics as M
from . import plots

_CSS = """
body{font-family:system-ui,-apple-system,sans-serif;margin:1.5rem auto;max-width:1080px;color:#222}
h1{margin-bottom:.2rem} .sub{color:#666;margin-top:0}
.cards{display:flex;gap:12px;flex-wrap:wrap;margin:1rem 0}
.card{border:1px solid #ddd;border-radius:10px;padding:10px 18px;min-width:130px}
.card .v{font-size:1.5rem;font-weight:700} .card .k{color:#666;font-size:.85rem}
table{border-collapse:collapse;margin:1rem 0;font-size:.92rem}
td,th{border:1px solid #ddd;padding:4px 10px;text-align:right}
th{background:#f6f6f6} .neg{color:#c0392b}
footer{color:#999;font-size:.8rem;margin-top:2rem}
"""


def _card(label: str, value: str) -> str:
    return (f'<div class="card"><div class="v">{value}</div>'
            f'<div class="k">{label}</div></div>')


def tear_sheet(
    returns: pd.Series,
    benchmark: pd.Series | None = None,
    rf: float = DEFAULT_RF,
    periods: int = TRADING_DAYS,
    title: str = "Portfolio Tear Sheet",
    output: str | None = "tear_sheet.html",
) -> str:
    """Build the report; returns the HTML string and writes `output` if set."""
    rets = returns.dropna()
    if len(rets) < 20:
        raise ValueError("need at least 20 return observations for a tear sheet")
    name = rets.name or "Portfolio"

    summary = M.summary(rets, rf=rf, periods=periods, bench=benchmark,
                        name=str(name)).to_frame()
    if benchmark is not None:
        summary["Benchmark"] = M.summary(benchmark.dropna(), rf=rf,
                                         periods=periods, name="Benchmark")

    headline = [
        _card("CAGR", f"{M.cagr(rets, periods):.2%}"),
        _card("Sharpe", f"{M.sharpe(rets, rf, periods):.2f}"),
        _card("Sortino", f"{M.sortino(rets, rf, periods):.2f}"),
        _card("Max Drawdown", f"{M.max_drawdown(rets):.1%}"),
        _card("Volatility", f"{M.ann_vol(rets, periods):.2%}"),
        _card("Win Rate", f"{M.win_rate(rets):.1%}"),
    ]

    panel = rets.to_frame(str(name))
    if benchmark is not None:
        panel["Benchmark"] = benchmark
    window = min(max(periods, 60), len(rets) - 1)

    figs = [
        plots.growth_chart(panel, title="Cumulative Growth", log_scale=True),
        plots.drawdown_chart(panel, title="Drawdowns"),
        plots.monthly_heatmap(rets, title="Monthly Returns"),
        plots.rolling_chart(M.rolling_sharpe(rets, window, rf, periods).dropna(),
                            f"Rolling Sharpe ({window} periods)", yformat=".2f"),
        plots.annual_returns_chart(panel, title="Annual Returns"),
    ]

    dd = M.drawdown_table(rets, top=8)
    if not dd.empty:
        for c in ("Start", "Trough", "Recovery"):
            dd[c] = pd.to_datetime(dd[c]).dt.strftime("%Y-%m-%d").fillna("ongoing")
        dd["Depth"] = dd["Depth"].map("{:.2%}".format)

    parts = [f"<title>{title}</title><style>{_CSS}</style>",
             f"<h1>{title}</h1>",
             f'<p class="sub">{rets.index[0]:%b %Y} – {rets.index[-1]:%b %Y} · '
             f'{len(rets)} periods · generated by '
             f'<a href="https://github.com/Realosunboy6/free-portfolio-visualizer">portlab</a></p>',
             '<div class="cards">', *headline, "</div>"]
    for i, fig in enumerate(figs):
        parts.append(fig.to_html(full_html=False,
                                 include_plotlyjs="inline" if i == 0 else False))
    parts.append("<h2>Metrics</h2>")
    parts.append(summary.map(
        lambda v: f"{v:,.4f}" if isinstance(v, float) else v).to_html())
    parts.append("<h2>Worst Drawdowns</h2>")
    parts.append(dd.to_html(index=False) if not dd.empty else "<p>None.</p>")
    parts.append("<footer>Past performance does not guarantee future results. "
                 "Not investment advice.</footer>")

    html = "\n".join(parts)
    if output:
        with open(output, "w") as f:
            f.write(html)
    return html
